In [1]:
%pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/28/75/3b679b41713bb60e2e8f6e2f87be72c971c9e718b1c17b8f8749240ddca8/numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 131.3 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.2 kB 130.4 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.2 kB 130.4 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.2 kB 140.3 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 154.0 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 162.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ------------------------


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# создание массива на базе списка
lst_1 = [10, 20, 30]   # массивы однотипные

lst_1

[10, 20, 30]

In [4]:
arr_1 = np.array(lst_1)

arr_1

array([10, 20, 30])

In [12]:
# создание 1 - мерного массива из нулей
arr_2 = np.zeros((2,3)) 
arr_2

array([[0., 0., 0.],
       [0., 0., 0.]])

- 1-мерный массив (вектор-строка)
- 2-мерный массивы (вектор-столбец, матрица)

In [13]:
# 1-мерный массив
np.zeros(3)

array([0., 0., 0.])

In [28]:
# 2-мерные массивы

# аналог вектор-столбца
np.empty((5,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.81019663e-310]])

In [26]:
# аналог матрицы 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- генерация массивов со случайными значениями

In [51]:
# 1-мерный массив случайных целых значений

# np.random.randint(30)
# np.random.randint(10, size=7)
np.random.randint(-5, 10, size=7)


array([ 9,  2,  9,  3,  6, -3,  8])

In [66]:
# 2-мерный массив случайных целых значений
np.random.randint(-5, 10, size=(2,3))

array([[ 6, -1,  0],
       [ 2, -3,  6]])

In [67]:
# массив случайных чисел с плавающей точкой
# из нормального (гауссова) распределения
np.random.randn(3, 4)

array([[-0.82240303, -0.29744014,  0.2934663 ,  0.50206658],
       [ 0.77945113,  0.0183671 , -0.8441534 ,  1.29387875],
       [-0.69921142,  0.70242586,  0.54850036,  0.94933909]])

- атрибуты

In [68]:
# форма массива
arr_1.shape

(3,)

In [69]:
arr_2.shape

(2, 3)

In [71]:
# тип данных
arr_1.dtype

dtype('int32')

In [72]:
arr_2.dtype

dtype('float64')

In [73]:
# объем занимаемой памяти (в байтах)
arr_1.nbytes

12

In [74]:
arr_2.nbytes

48

- методы 

In [98]:
# конвертация типа данных
arr_3 = np.random.randint(-5, 5, size=(2,3))
arr_3

array([[-5, -4,  2],
       [-2,  2, -1]])

In [77]:
arr_3.dtype

dtype('int32')

In [78]:
arr_3.astype("float16")

array([[ 4., -1., -2.],
       [-1., -5.,  0.]], dtype=float16)

In [89]:
# минимальное значение по всему массиву
arr_3.min()

-5

In [94]:
# минимальное значение по какой-то оси
arr_3.min(0)

array([-1, -5, -2])

In [104]:
# сортировка массива
arr_3.sort(0)


In [105]:
arr_3

array([[-5, -4, -1],
       [-2,  2,  2]])

In [107]:
arr_4 = np.random.randint(-5, 5, size=(5,5))
arr_4

array([[-3,  3, -2,  3, -2],
       [-3, -2, -2, -4, -1],
       [-3, -1, -4, -5, -1],
       [ 0, -3, -2, -2, -4],
       [ 4,  4,  3, -4,  3]])

In [108]:
arr_4[0][0]

-3

In [109]:
arr_4[0,0]

-3

In [115]:
arr_4[:,:3]

array([[-3,  3, -2],
       [-3, -2, -2],
       [-3, -1, -4],
       [ 0, -3, -2],
       [ 4,  4,  3]])