In [1]:
%pip install pandas


  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/df/92/a3fa053c74198f9f0224b2c04dc74f41d2e14e30329c082f7a657f9ca4c5/pandas-2.1.3-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
     ---------------------------------------- 0.0/341.8 kB ? eta -:--:--
     - -------------------------------------- 10.2/341.8 kB ? eta -:--:--
     --- --------------------------------- 30.7/341.8 kB 435.7 kB/s eta 0:00:01
     --- --------------------------------- 30.7/341.8 kB 435.7 kB/s eta 0:00:01
     --- --------------------------------- 30.7/341.8 kB 435.7 kB/s eta 0:00:01
     ---- -------------------------------- 41.0/341.8 kB 178.6 kB/s eta 0:00:02
     ------- ----------------------------- 71.7/341.8 kB 262.6 kB/s eta 0:00:02
     ----------- ------------------


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## Pandas - библиотека для работы с данными

In [2]:
import pandas as pd

- объекты класса (типа) Series

In [3]:
# Series - 1-мерный массив данных
# создание на базе списка
s0 = pd.Series([10,20,30,40])
s0

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
s0.to_numpy()

array([10, 20, 30, 40], dtype=int64)

In [5]:
# создание на базе словаря
d0 = {'a':100, 5:203, 0:27}
s1 = pd.Series(d0)
s1

a    100
5    203
0     27
dtype: int64

In [6]:
# явные индексы
s1[0]

27

In [8]:
s1["a"]

100

In [14]:
# неявные индексы
# атрибут индексатор для НЕявных индексов 
# s1.iloc[0]
s1.iloc[-1]

27

In [18]:
# атрибут индексатор для явных индексов 
s1.loc[0]

27

In [20]:
s1.shape

(3,)

In [21]:
s1.dtype

dtype('int64')

In [22]:
s1.index

Index(['a', 5, 0], dtype='object')

In [23]:
s1.values

array([100, 203,  27], dtype=int64)

In [39]:
# Данные по населению городов Якутии
pop_d = {
    "Yakutsk": 318768,
    "Neryungri": 57009,
    "Vilyusk": 11095
}

pop_s = pd.Series(pop_d)
pop_s

Yakutsk      318768
Neryungri     57009
Vilyusk       11095
dtype: int64

In [ ]:
# 1. вывести значение населения выбранного города 
# 2. сделать срез от нер до вил


In [32]:
pop_s["Yakutsk"]

318768

In [34]:
pop_s["Neryungri":"Vilyusk"]

Neryungri    57009
Vilyusk      11095
dtype: int64

- Объект класса DataFrame

In [35]:
d1 = {
    "col 1": {"row 1": 1000, "row 2": 2000},
    "col 2": {"row 2": 3000, "row 3": 4000},
    "col 3": {"row 1": 5000, "row 4": 6000}
}

df0 = pd.DataFrame(d1)
df0

col 1   col 2   col 3
row 1  1000.0     NaN  5000.0
row 2  2000.0  3000.0     NaN
row 3     NaN  4000.0     NaN
row 4     NaN     NaN  6000.0

In [36]:
area_d = {
    "Yakutsk": 122,
    "Neryungri": 99,
    "Vilyusk": 15
}

area_s = pd.Series(area_d)
area_s

Yakutsk      122
Neryungri     99
Vilyusk       15
dtype: int64

In [42]:
ykt_df = pd.DataFrame({"population": pop_s, "area": area_s})
ykt_df

population  area
Yakutsk        318768   122
Neryungri       57009    99
Vilyusk         11095    15

In [48]:
# данные из столбца
# ykt_df["area"]
ykt_df.loc[: "Neryungri", "area"]

Yakutsk      122
Neryungri     99
Name: area, dtype: int64

In [45]:
# данные из строк
# ykt_df.loc["Yakutsk", "population"]
ykt_df.loc["Yakutsk", :]

population    318768
area             122
Name: Yakutsk, dtype: int64

- маскированифе

In [49]:
import numpy as np

np.random.seed(0)

arr0 = np.random.randint(10, size=5)
arr0

array([5, 0, 3, 3, 7])

In [50]:
arr0 >= 5

array([ True, False, False, False,  True])

In [51]:
# города Якутии с населением больше 15000

mask = ykt_df["population"] > 15000
mask

Yakutsk       True
Neryungri     True
Vilyusk      False
Name: population, dtype: bool

In [52]:
ykt_df.loc[mask, :]

population  area
Yakutsk        318768   122
Neryungri       57009    99

In [53]:
ykt_df.loc[ykt_df["population"] > 15000]

population  area
Yakutsk        318768   122
Neryungri       57009    99